#ifndef HPCSSUPPORT_GLOBAL_H
#define HPCSSUPPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HPCSSUPPORT_LIBRARY)
#  define HPCSSUPPORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HPCSSUPPORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HPCSSUPPORT_GLOBAL_H
