/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp dbusinterface.xml -i dbusinterface.h -a DBusInterfaceAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSINTERFACEADAPTOR_H_1498406530
#define DBUSINTERFACEADAPTOR_H_1498406530

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "dbusinterface.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface dataloader.loader
 */
class LoaderAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "dataloader.loader")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"dataloader.loader\">\n"
"    <method name=\"loadData\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"formatTag\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"loadOption\"/>\n"
"      <arg direction=\"out\" type=\"(bsa(ssssssa(dd)))\" name=\"pack\"/>\n"
"      <annotation value=\"IPCDBusDataPack\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"loadDataHint\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"formatTag\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"hint\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"loadOption\"/>\n"
"      <arg direction=\"out\" type=\"(bsa(ssssssa(dd)))\" name=\"pack\"/>\n"
"      <annotation value=\"IPCDBusDataPack\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"loadDataFile\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"formatTag\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"filePath\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"loadOption\"/>\n"
"      <arg direction=\"out\" type=\"(bsa(ssssssa(dd)))\" name=\"pack\"/>\n"
"      <annotation value=\"IPCDBusDataPack\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"supportedFileFormats\">\n"
"      <arg direction=\"out\" type=\"a(sssa(s))\" name=\"supportedFileFormats\"/>\n"
"      <annotation value=\"IPCDBusSupportedFileFormatVec\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    LoaderAdaptor(QObject *parent);
    virtual ~LoaderAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    IPCDBusDataPack loadData(const QString &formatTag, int loadOption);
    IPCDBusDataPack loadDataFile(const QString &formatTag, const QString &filePath, int loadOption);
    IPCDBusDataPack loadDataHint(const QString &formatTag, const QString &hint, int loadOption);
    IPCDBusSupportedFileFormatVec supportedFileFormats();
Q_SIGNALS: // SIGNALS
};

#endif
