/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp dbusinterface.xml -i dbusinterface.h -p DBusInterfaceInterface
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "DBusInterfaceInterface.h"

/*
 * Implementation of interface class DataloaderLoaderInterface
 */

DataloaderLoaderInterface::DataloaderLoaderInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

DataloaderLoaderInterface::~DataloaderLoaderInterface()
{
}

