/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "DBusInterfaceAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class LoaderAdaptor
 */

LoaderAdaptor::LoaderAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

LoaderAdaptor::~LoaderAdaptor()
{
    // destructor
}

IPCDBusDataPack LoaderAdaptor::loadData(const QString &formatTag)
{
    // handle method call dataloader.loader.loadData
    IPCDBusDataPack pack;
    QMetaObject::invokeMethod(parent(), "loadData", Q_RETURN_ARG(IPCDBusDataPack, pack), Q_ARG(QString, formatTag));
    return pack;
}

IPCDBusDataPack LoaderAdaptor::loadDataFile(const QString &formatTag, const QString &filePath)
{
    // handle method call dataloader.loader.loadDataFile
    IPCDBusDataPack pack;
    QMetaObject::invokeMethod(parent(), "loadDataFile", Q_RETURN_ARG(IPCDBusDataPack, pack), Q_ARG(QString, formatTag), Q_ARG(QString, filePath));
    return pack;
}

IPCDBusDataPack LoaderAdaptor::loadDataHint(const QString &formatTag, const QString &hint)
{
    // handle method call dataloader.loader.loadDataHint
    IPCDBusDataPack pack;
    QMetaObject::invokeMethod(parent(), "loadDataHint", Q_RETURN_ARG(IPCDBusDataPack, pack), Q_ARG(QString, formatTag), Q_ARG(QString, hint));
    return pack;
}

IPCDBusSupportedFileFormatVec LoaderAdaptor::supportedFileFormats()
{
    // handle method call dataloader.loader.supportedFileFormats
    IPCDBusSupportedFileFormatVec supportedFileFormats;
    QMetaObject::invokeMethod(parent(), "supportedFileFormats", Q_RETURN_ARG(IPCDBusSupportedFileFormatVec, supportedFileFormats));
    return supportedFileFormats;
}

