/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: 
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSINTERFACEINTERFACE_H
#define DBUSINTERFACEINTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "common/ipcinterface.h"

/*
 * Proxy class for interface dataloader.loader
 */
class DataloaderLoaderInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "dataloader.loader"; }

public:
    DataloaderLoaderInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~DataloaderLoaderInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<IPCDBusDataPack> loadData(const QString &formatTag)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(formatTag);
        return asyncCallWithArgumentList(QStringLiteral("loadData"), argumentList);
    }

    inline QDBusPendingReply<IPCDBusDataPack> loadDataFile(const QString &formatTag, const QString &filePath)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(formatTag) << QVariant::fromValue(filePath);
        return asyncCallWithArgumentList(QStringLiteral("loadDataFile"), argumentList);
    }

    inline QDBusPendingReply<IPCDBusDataPack> loadDataHint(const QString &formatTag, const QString &hint)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(formatTag) << QVariant::fromValue(hint);
        return asyncCallWithArgumentList(QStringLiteral("loadDataHint"), argumentList);
    }

    inline QDBusPendingReply<IPCDBusSupportedFileFormatVec> supportedFileFormats()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("supportedFileFormats"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace dataloader {
  typedef ::DataloaderLoaderInterface loader;
}
#endif
